---
- name: Configure ports.conf
  template:
    src: Common/ports.conf.j2
    dest: /etc/{{apache_pkg}}/ports.conf
  when: apache_sites
  notify:
    - Restart {{apache_pkg}}

- name: Enable Modules - Debian
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: apache_mods
  when: ansible_os_family == 'Debian' and apache_mods
