---
- name: Install 'apache' package
  package:
    name: '{{ apache-pkg }}'
    state: present

- name: Install other required packages
  package:
    name: '{{ item }}'
    state: present
  with_items: apache-pkg-other
