---
- name: Install 'apache' package - Debian
  apt:
    name: '{{ apache_pkg }}'
    state: present
  when: ansible_os_family == 'Debian'

- name: Install other required packages
  apt:
    name: '{{ item }}'
    state: present
  with_items: apache_pkg_other
  when: apache_pkg_other
